[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "python_template"
authors = [{name = "Andy Freeland", email = "andy@andyfreeland.net"}]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Private :: Do Not Upload",
]
dynamic = ["version", "description"]
requires-python = ">=3.10"

[project.urls]
Home = "https://github.com/rouge8/python-template"

[tool.pytest.ini_options]
addopts = "--strict-config --strict-markers"

[tool.mypy]
strict = true
allow_redefinition = true
warn_unreachable = true
